name: Destroy
on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Which enviroment to remove AWS recources for ?
                options:
                    - staging
                    - prod
